### Лучше пройти то же самое от DLS


In [1]:
import numpy as np
import tensorflow as tf
import tensorflow.python.util.deprecation as deprecation
deprecation._PRINT_DEPRECATION_WARNINGS = False

In [2]:
a = tf.constant(3.0, dtype=tf.float32)
b = tf.constant(4.0) # also tf.float32 implicitly
total = a + b
print(a)
print(b)
print(total)

Tensor("Const:0", shape=(), dtype=float32)
Tensor("Const_1:0", shape=(), dtype=float32)
Tensor("add:0", shape=(), dtype=float32)


In [25]:
writer = tf.summary.FileWriter('.')
writer.add_graph(tf.get_default_graph())
writer.flush()

In [4]:
sess = tf.Session()
print(sess.run(total))

7.0


In [5]:
print(sess.run({'ab':[a, [b, total]], 'total':total}))

{'ab': [3.0, [4.0, 7.0]], 'total': 7.0}


In [6]:
vec = tf.random_uniform(shape=(3,))
out1 = vec + 1
out2 = vec + 2
print(sess.run(vec))
print(sess.run(vec))
print(sess.run([out1, out2]))

[0.15854716 0.01456761 0.0474354 ]
[0.09198487 0.8608322  0.9111569 ]
[array([1.6111382, 1.0350314, 1.1125209], dtype=float32), array([2.6111383, 2.0350313, 2.112521 ], dtype=float32)]


# Feeding

In [7]:
x = tf.placeholder(tf.float32)
y = tf.placeholder(tf.float32)
z = x + y

In [8]:
print(sess.run(z, feed_dict={x: 3, y: 4.5}))
print(sess.run(z, feed_dict={x: [1, 3, 1], y: [2, 4, 1]}))

7.5
[3. 7. 2.]


In [9]:
print(sess.run(z, feed_dict={x: 3, y: [1, 2]}))


[4. 5.]


# Layers

In [10]:
x = tf.placeholder(tf.float32, shape=[None, 3])
linear_model = tf.layers.Dense(units=1)
y = linear_model(x)

In [11]:
init = tf.global_variables_initializer()
sess.run(init)

In [12]:
sess.run([linear_model.weights], feed_dict={x: [[1, 2, 3], [4, 5, 6]]})

[[array([[-1.00066   ],
         [ 0.9322866 ],
         [ 0.09345937]], dtype=float32), array([0.], dtype=float32)]]

In [13]:
sess.run([y], feed_dict={x: [[1, 2, 3], [4, 5, 6]]})

[array([[1.1442914],
        [1.2195497]], dtype=float32)]

In [14]:
x = tf.placeholder(tf.float32, shape=[None, 3])
y = tf.layers.dense(x, units=1)

init = tf.global_variables_initializer()
sess.run(init)

print(sess.run(y, {x: [[1, 2, 3], [4, 5, 6]]}))

[[-0.6006839]
 [-2.8389626]]


# Training

In [19]:
x = tf.constant([[1], [2], [3], [4]], dtype=tf.float32)
y_true = tf.constant([[0], [-1], [-2], [-3]], dtype=tf.float32)

In [20]:
linear_model = tf.layers.Dense(units=1)

y_pred = linear_model(x)

In [21]:
sess = tf.Session()
init = tf.global_variables_initializer()
sess.run(init)

print(sess.run(y_pred))

[[1.0418633]
 [2.0837266]
 [3.1255898]
 [4.1674533]]


In [22]:
loss = tf.losses.mean_squared_error(labels=y_true, predictions=y_pred)
sess.run(loss)

22.059727

In [23]:
optimizer = tf.train.GradientDescentOptimizer(0.01)
train = optimizer.minimize(loss)

In [24]:
for i in range(100):
  _, loss_value = sess.run((train, loss))
  print(loss_value)

22.059727
15.422407
10.816221
7.619397
5.400506
3.860186
2.7907152
2.0479612
1.531913
1.1731751
0.9235956
0.74976265
0.6284925
0.5436985
0.48421848
0.44230705
0.41258988
0.39133805
0.37596357
0.3646713
0.3562153
0.34973097
0.34461835
0.34046143
0.33697104
0.3339469
0.3312498
0.32878327
0.32648027
0.32429433
0.32219303
0.32015404
0.3181618
0.31620523
0.31427705
0.31237194
0.31048623
0.30861726
0.30676332
0.3049232
0.30309594
0.30128086
0.2994775
0.2976856
0.29590482
0.29413494
0.29237592
0.2906275
0.28888965
0.28716224
0.2854452
0.28373858
0.28204212
0.2803558
0.27867952
0.2770133
0.2753571
0.2737108
0.27207428
0.2704476
0.26883066
0.26722333
0.26562566
0.26403752
0.26245892
0.26088968
0.25932992
0.2577794
0.2562382
0.25470617
0.2531833
0.25166956
0.25016487
0.24866919
0.24718243
0.24570459
0.24423555
0.24277526
0.24132378
0.2398809
0.23844673
0.2370211
0.23560394
0.23419535
0.23279512
0.23140325
0.23001976
0.22864449
0.22727749
0.22591862
0.2245679
0.22322522
0.22189057
0.220564
0.2192

# Full program

In [26]:
x = tf.constant([[1], [2], [3], [4]], dtype=tf.float32)
y_true = tf.constant([[0], [-1], [-2], [-3]], dtype=tf.float32)

linear_model = tf.layers.Dense(units=1)

y_pred = linear_model(x)
loss = tf.losses.mean_squared_error(labels=y_true, predictions=y_pred)

optimizer = tf.train.GradientDescentOptimizer(0.01)
train = optimizer.minimize(loss)

init = tf.global_variables_initializer()

sess = tf.Session()
sess.run(init)
for i in range(100):
  _, loss_value = sess.run((train, loss))
  print(loss_value)

print(sess.run(y_pred))

28.003242
19.556828
13.695286
9.627338
6.8039303
4.8440886
3.48346
2.5386178
1.8822852
1.4261476
1.1089257
0.88809836
0.7341616
0.6266432
0.55133754
0.49838787
0.46095473
0.43429232
0.4151075
0.40111542
0.3907305
0.3828526
0.3767183
0.37179768
0.3677234
0.36424017
0.36117107
0.3583932
0.35582125
0.3533961
0.35107648
0.3488341
0.346649
0.3445074
0.34239975
0.34031934
0.33826157
0.33622319
0.3342018
0.33219597
0.33020443
0.32822657
0.32626158
0.32430905
0.32236886
0.3204406
0.31852415
0.31661934
0.31472605
0.3128441
0.31097358
0.30911422
0.307266
0.3054288
0.30360273
0.3017875
0.29998308
0.29818952
0.29640672
0.29463458
0.29287297
0.29112196
0.28938138
0.28765118
0.28593135
0.2842218
0.28252253
0.28083336
0.2791543
0.27748528
0.27582625
0.2741771
0.27253783
0.27090842
0.26928866
0.26767865
0.26607823
0.26448745
0.26290604
0.26133418
0.25977173
0.25821862
0.2566747
0.25514016
0.25361463
0.25209838
0.25059107
0.24909286
0.24760357
0.24612315
0.24465163
0.24318893
0.24173494
0.24028961
0.23